apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.django.appName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.django.appName }}
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # Immediate response for scaling up
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60  # Can add up to 4 pods per minute
      - type: Percent
        value: 50
        periodSeconds: 60  # Or scale up by 50% of current pods per minute
      selectPolicy: Max  # Use the highest policy when both apply
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60  # Remove 1 pod per minute
      - type: Percent
        value: 10
        periodSeconds: 60  # Or scale down by 10% of current pods per minute
      selectPolicy: Min  # Use the lowest policy when both apply
